### ISSUE TITLE
TVShows

### ISSUE THREAD

**Issue by jammi** [ilucas/TVShows#1]
Hi, it seems like you're the most recent maintainer of TVShows. Victorpimentel's fork hasn't seen any updates in a couple of years, so would you mind distributing builds of your fork? I tried to compile yours, but it ended up in dependency hell, so I gave up.

**Comment by ilucas** [comment]
Did you tried to compile the develop branch?
I´m not publishing builds yet because there´s not much made, the biggest change is that TVShows is now a standalone app (easier to develop).

**Comment by jammi** [comment]
Yes I did, just getting new builds around would be great and for 1080p in HiDPI mode ("960x540") the prefpane version isn't usable to begin with.

**Comment by gayprogrammer** [comment]
I was able to load the submodule dependencies with: `git submodule init && git submodule update --recursive` (the readme suggests `git clone --recursive` but points to the original repo). 

I ran into `error: use of '@import' when modules are disabled`. I loaded it into Xcode 6.3.1 and set `Build Settings : All : Apple LLVM 6.0 - Language - Modules : Enable Modules (C and Objective-C)` to Yes.  But the error will not go away.

**Comment by ilucas** [comment]
Try `git clone --recursive -b develop git@github.com:ilucas/TVShows.git` and open  the TVShows.xcworkspace

**Comment by oskarkrawczyk** [comment]
@ilucas Do you have by any chance plans on releasing builds of your fork? Tried to compile it myself but had very little luck.

**Comment by ilucas** [comment]
No, i'm not making a release any time soon. i'm not having to much free time now to work in this project. sorry :(

**Comment by jammi** [comment]
I ran this:

```
$ git clone -b develop --recurse-submodules --recursive git@github.com:ilucas/TVShows.git
... (ok)
$ cd TVShows
TVShows@develop$ git submodule init && git submodules update --recursive
... (ok)
TVShows@develop$ xcodebuild
```

..which resulted in the following failure (full log): https://gist.github.com/jammi/892aad1a38f22ed2eb73

**Comment by mintyPT** [comment]
Did someone ended up making this work?

**Comment by jannae** [comment]
Yes, I was just able to build after satisfying dependencies. As @ilucas said, there is not much else to this fork other than it no longer requires running as a prefpane. From what I can tell, this is still very much in development, and there is not yet a releasable app here. It would be great if a dev could fork this and put a little time into it, this app is great!

In order to build this for XCode 7.0.1, I did the following:
1. `git clone --recursive -b develop git@github.com:ilucas/TVShows.git`
2. `pod install` To satisfy dependencies. (you will need [CocoaPods](https://cocoapods.org))
3. Open the project in XCode.
4. Enable modules for the project. (Graphics and a write up on this [here](http://stackoverflow.com/questions/18947516/import-vs-import-ios-7)). 
5. Click the Build button from inside XCode. (for some reason, using `xcodebuild` in terminal never worked for me.
6. The standalone app will open. You'll see there isn't much to it... yet! :)

**Comment by ilucas** [comment]
Latest build can be found here: [v3.0.0-alpha.1](https://github.com/ilucas/TVShows/releases/tag/v3.0.0-alpha.1)
